### ISSUE TITLE
failed: execute of template failed: template: talk/single.html:16:9:

### ISSUE THREAD

**Issue by Tai-Rocha** [hugo-apero/hugo-apero-docs#105]
Hi everyone!  After an upgrade R to Version 4.1.2, blogdown to 1.6 and Hugo-Aperó to 0.89.4, I can not render my site locally with blogdown:::serve_site() command and I can not update the site at Netlify.

The error I receive
`Launching the server via the command:
  hugo server --bind 127.0.0.1 -p 4321 --themesDir themes -t hugo-apero -D -F --navigateToChanged
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: talk/single.html:16:9: executing "main" at <partial "shared/event-details.html" .>: error calling partial: execute of template failed: template: partials/shared/event-details.html:56:30: executing "partials/shared/event-details.html" at <partial "shared/date-range.html" .>: error calling partial: "/home/tai-rocha/Documents/Github/tainaweb_en/themes/hugo-apero/layouts/partials/shared/date-range.html:8:36": execute of template failed: template: partials/shared/date-range.html:8:36: executing "partials/shared/date-range.html" at <time .>: error calling time: unable to parse date: 20212-10-01`

Any idea about how to fix it?

Thanks in advance !!

**Comment by gadenbuie** [comment]
It looks like you have a typo in the date field of one of your posts. Try running **Find All** on the term `20212-10-01` (I'm guessing that post was supposed to be `2021-10-01`).

**Comment by Tai-Rocha** [comment]
Thanks for the quick response!! I corrected the wrong date. But now I receive another error: 

`Launching the server via the command:
  hugo server --bind 127.0.0.1 -p 4321 --themesDir themes -t hugo-apero -D -F --navigateToChanged
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:3:8: executing "_default/single.html" at <partial "head.html" .>: error calling partial: execute of template failed: template: _internal/schema.html:24:82: executing "_internal/schema.html" at <.Params.tags>: range can't iterate over Data Science`

 I am not sure if need to change something in the single.html and head.html

**Comment by apreshill** [comment]
Make sure your tags looks like this:

```
tags:
  - powerpoint
  - rmarkdown
```

**Comment by Tai-Rocha** [comment]
Many thanks @apreshill  and @gadenbuie !! I just needed to add an "Enter" in tag
