### ISSUE TITLE
Linking pdf file in website

### ISSUE THREAD

**Issue by bbitarello** [hugo-apero/hugo-apero-docs#108]
Hi, I am trying to include pdf files into my website. I have tried putting them into the /static/files/ folder.
Code of all my attempts below:

`<i class="fas fa-file-pdf"></i> [syllabus (fall 2021)](/static/files/syllabus.pdf) AND
 <i class="fas fa-file-pdf"></i> [syllabus (fall 2021)](/files/syllabus.pdf)
`
All of those attempts lead to a 404 when clicked on.
I appreciate your help!

**Comment by apreshill** [comment]
Hi- your PDF files appear to be named:
https://github.com/bbitarello/bitarellolab/tree/main/static/files

+ `110-2021-Course information.pdf`
+ `Simple_CV.pdf`

When I locally serve your site, I can access them if I use the file names I see in `static/files/`
<img width="1232" alt="Screen Shot 2022-01-23 at 2 49 11 PM" src="https://user-images.githubusercontent.com/12160301/150701185-bab3fd47-f591-4871-b722-66cc8c15ddf4.png">

<img width="1232" alt="Screen Shot 2022-01-23 at 2 50 44 PM" src="https://user-images.githubusercontent.com/12160301/150701209-048ac569-0ed8-4bac-a594-8263c66bf0dd.png">

**Comment by bbitarello** [comment]
oh damn, I totally missed that! I fixed the names now but I am getting the same errors. I am embarrassed about that lol. I didn't name that file originally, so I didn't pay attention to that. Thank you!
